import './globals.scss';
import { Heebo } from 'next/font/google';
import Navigation from './Navigation';

const heebo = Heebo({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Next Example | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <div className="topMessage">Free shipping worldwide!</div>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
